### ISSUE TITLE
Feature Request: Add Video Source Support

### ISSUE THREAD

**Issue by JIceberg** [serivesmejia/EOCV-Sim#18]
OpenCV has support for video sources. I know for a fact that in python you can do
```python
import cv2
vid = cv2.VideoCapture('video.mp4')
success, img = vid.read()
while success:
  success, img = vid.read()
```
and it works just fine with `img` representing each image frame. I'm sure Java has something similar, if not C++. Would be great if I can bypass the camera and simply use an mp4 or other video format to test pipelines (super useful for remote stuff).

**Comment by serivesmejia** [comment]
Added in [v2.1.0](https://github.com/serivesmejia/EOCV-Sim/releases/tag/v2.1.0)
